[expo-notifications] Fix `didn't find class "host.exp.exponent.notifications.NotificationsScoper"` (#9731)
# Why

Fixes:
```
2020-08-13 11:57:04.991 6351-6401/? E/unknown:DisabledDevSupportManager: Caught exception
    java.lang.IllegalStateException: Unable to instantiate AppLoader!
        at expo.modules.notifications.notifications.interfaces.b.a(NotificationsScoper.java:10)
        at expo.modules.notifications.notifications.handling.NotificationsHandler.<init>(NotificationsHandler.java:3)
        at expo.modules.notifications.NotificationsPackage.createExportedModules(NotificationsPackage.java:1)
        at org.unimodules.adapters.react.e.c(ReactModuleRegistryProvider.java:6)
        at host.exp.exponent.experience.k.createNativeModules(DetachedModuleRegistryAdapter.java:2)
        at versioned.host.exp.exponent.ExponentPackage.createNativeModules(ExponentPackage.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:7)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:8)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:6)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:8)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:6)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:1)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:12)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: host.exp.exponent.notifications.NotificationsScoper
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at expo.modules.notifications.notifications.interfaces.b.a(NotificationsScoper.java:4)
        at expo.modules.notifications.notifications.handling.NotificationsHandler.<init>(NotificationsHandler.java:3) 
        at expo.modules.notifications.NotificationsPackage.createExportedModules(NotificationsPackage.java:1) 
        at org.unimodules.adapters.react.e.c(ReactModuleRegistryProvider.java:6) 
        at host.exp.exponent.experience.k.createNativeModules(DetachedModuleRegistryAdapter.java:2) 
        at versioned.host.exp.exponent.ExponentPackage.createNativeModules(ExponentPackage.java:31) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:7) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:8) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:6) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:8) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:6) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:1) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:12) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "host.exp.exponent.notifications.NotificationsScoper" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/abc.efg.hij-ZXYhUJy9UgNFSY_H9cBAMA==/base.apk"],nativeLibraryDirectories=[/data/app/abc.efg.hij-ZXYhUJy9UgNFSY_H9cBAMA==/lib/arm64, /data/app/abc.efg.hij-ZXYhUJy9UgNFSY_H9cBAMA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at expo.modules.notifications.notifications.interfaces.b.a(NotificationsScoper.java:4) 
        at expo.modules.notifications.notifications.handling.NotificationsHandler.<init>(NotificationsHandler.java:3) 
        at expo.modules.notifications.NotificationsPackage.createExportedModules(NotificationsPackage.java:1) 
        at org.unimodules.adapters.react.e.c(ReactModuleRegistryProvider.java:6) 
        at host.exp.exponent.experience.k.createNativeModules(DetachedModuleRegistryAdapter.java:2) 
        at versioned.host.exp.exponent.ExponentPackage.createNativeModules(ExponentPackage.java:31) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:7) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:8) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:6) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:8) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:6) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:1) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:12) 
        at java.lang.Thread.run(Thread.java:764) 
```
(from https://exponent-internal.slack.com/archives/C1QNF5L3C/p1597315400011200)

# How

Added a proguard's rule. 

# Test Plan

- builds `APK` using those options:
```
      minifyEnabled true
      useProguard true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
      consumerProguardFiles 'proguard-rules.pro'
``` 
and confirms that `host.exp.exponent.notifications.NotificationsScoper` exists in the bundle 
![image](https://user-images.githubusercontent.com/9578601/90144630-58e1ce80-dd7f-11ea-8c9a-b583f4a32ac8.png)