[template-files] Configure podspec for Reanimated and TurboModules (#10090)
# Why

Shell apps for iOS fail to build, `ExpoKit`, which is used as a pod when building a shell app for iOS is missing some required files and flags.

# How

- Looked into adding TurboModules commit and went through notable changes made to `Exponent.xcodeproj`.
- Added `.cpp` files for Reanimated v2.
- Had to add `\"$(PODS_ROOT)/Headers/Private/React-Core\"` to header search paths, otherwise `RCTCxxBridgeDelegate.h` header wasn't being found (for some reason it's a private header).

# Test Plan

I have verified manually that this fixes the following problem:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_EXReactAppManager", referenced from:
      objc-class-ref in libExpoKit.a(EXHeadlessAppRecord.o)
ld: symbol(s) not found for architecture x86_64
```