[Android][shell-app] Fix guava class duplication error
In shell-app code generation the line:
  implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
was being removed and without this line turtle fails to build shell-app giving error:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-18.0.jar (com.google.guava:guava:18.0) and jetified-listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)